[project]
name = "simli-python-sdk-starter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "aiortc",
    "websockets",
    "requests",
]

[project.optional-dependencies]
local = [
    "opencv-python",
    "pyaudio",
]
processing = [
    "numpy",
]

[tool.uv]
dev-dependencies = [
    "python-dotenv",
    "ruff",
    "uv",
]
